palette = "nord"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

right_format = "$cmd_duration"

[palettes.nord]
frost0  = "#8fbcbb"
frost1  = "#88c0d0"
frost2  = "#81a1c1"
frost3  = "#5e81ac"
snow0   = "#d8dee9"
snow1   = "#e5e9f0"
snow2   = "#eceff4"
dark0   = "#2e3440"
dark1   = "#3b4252"
dark2   = "#434c5e"
dark3   = "#4c566a"
red     = "#bf616a"
orange  = "#d08770"
yellow  = "#ebcb8b"
green   = "#a3be8c"
purple  = "#b48ead"

[username]
format = "[$user]($style)"
style_user = "bold frost1"
style_root = "bold red"
show_always = false

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_symbol = " "
style = "bold orange"
ssh_only = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncation_symbol = "…/"
style = "bold frost1"
read_only = " 󰌾"
read_only_style = "red"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "purple"
truncation_length = 24

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "dark3"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "="
deleted = "✘"
renamed = "»"
modified = "~"
staged = "+"
untracked = "?"
stashed = "≡"

[cmd_duration]
min_time = 2_000
format = "[$duration]($style)"
style = "yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[python]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[docker_context]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true
